### PR TITLE
relax constraints on link with error_message

### PR DESCRIPTION
**Pull request by pdowler**
Not sure if the additional example(s) in the error_message section help all that much. I can remove if they don't.

### CODE REVIEW

**Comment by Bonnarel** [comment]
agreed

**Review by mbtaylor — APPROVED** [review]

**Comment by mbtaylor** [comment]
I think the example text is worth having.

**Review by jd-au — APPROVED** [review]
Agree the example is useful

**Comment by jd-au** [comment]
I'll merge this before the TCG meeting unless there are objections beforehand.

**Comment by pdowler** [comment]
please merge
--
Patrick Dowler
Canadian Astronomy Data Centre
Victoria, BC, Canada

**Pull request merged**
