### PR TITLE
install inkscape in preview build; resolves #79

### LINKED ISSUE #79: Architecture diagram absent in auto-built PDF
The pre-release auto-pdf-preview currently available at https://github.com/ivoa-std/DataLink/releases/tag/auto-pdf-preview contains the PDF fallback text _("PDF fallback: A conversion from SVG to PDF failed. This is probably because inkscape is not installed. While SVG is not supported by the major TeX engines, it is recommended to commit built PDFs to the VCS.")_ where the architecture diagram should be.

I get something similar when I build it locally, but I never know whether that's my misconfiguration.

Should the arch diagram PDF be added to the commits?  At any rate something should be done to fix the auto-preview.

### PR DESCRIPTION
**Pull request by pdowler**
and exec inkscape --version in the CI and preview builds to help diagnose command-line compat issues

### CODE REVIEW

**Comment by gmantele** [comment]
Seems better but not yet enough apparently :(

There is no more error about inkscape not being found, but the passed parameter seems to be incorrect (see the workflow log - https://github.com/ivoa-std/DataLink/pull/81/checks):

```
inkscape --export-filename=role_diagram.pdf --export-type=pdf role_diagram.svg \
	|| cp ivoatex/svg-fallback.pdf role_diagram.pdf

** (inkscape:7320): WARNING **: 16:17:01.156: Invalid option --export-filename=role_diagram.pdf
```
The PDF generated in the artefact of the build workflow (https://github.com/ivoa-std/DataLink/suites/4269455685/artifacts/111029053) does confirm that no the diagram has been added to the document :(

**Comment by pdowler** [comment]
ubuntu-latest had inkscape 0.92 and 1.1 is the current stable version - it's working now with the ppa repo added (in CI build, should be the same in preview

**Review by jd-au — APPROVED** [review]
Architecture diagram now appears in the preview pdf

**Comment by msdemlei** [comment]
On Fri, Nov 05, 2021 at 09:43:07AM -0700, Grégory Mantelet wrote:
> Seems better but not yet enough apparently :(
> 
> There is no more error about inkscape not being found, but the passed parameter seems to be incorrect (see the workflow log - https://github.com/ivoa-std/DataLink/pull/81/checks):
> 
> ```
> inkscape --export-filename=role_diagram.pdf --export-type=pdf role_diagram.svg \
> 	|| cp ivoatex/svg-fallback.pdf role_diagram.pdf
> 
> ** (inkscape:7320): WARNING **: 16:17:01.156: Invalid option --export-filename=role_diagram.pdf
> ```
> The PDF generated in the artefact of the build workflow
> (https://github.com/ivoa-std/DataLink/suites/4269455685/artifacts/111029053)
> does confirm that no the diagram has been added to the document :(

While I'm totally sypathetic to Pat's concerns about committing build
artefacts, for the role diagram PDF I'm arguing that it should be in
the repo.  For one, changes are so rare that merge conflicts are
unlikely.

More importantly, though, inkscape is a fat dependency that probably
doubles the size of the CI container and its runtime.  Then, the
other, perhaps more rational SVG conversion options I've looked
at all suck in various ways.  Finally, inkscape itself isn't as
stable as I'd like a dependency of software of mine to be.  The
present problem is a consequence of this:
https://github.com/ivoa-std/ivoatex/pull/42#pullrequestreview-655908300,
I believe.

You could heal it by basing our CI container on some distro that
carries inkscape 1.

But really: just commit role_diagram.pdf and be done with it until
someone writes better and less voluminous SVG tooling (perhaps:
ghostscript or pdflatex can render SVG).

**Pull request merged**
