### PR TITLE
new changes in introduction in response to Pat's demand

### PR DESCRIPTION
**Pull request by Bonnarel**
related to issues #6 #7

### CODE REVIEW

**Comment by msdemlei** [comment]
Very frankly, I'm only very moderately excited about things like "data/metadata" that read like a law text gone stale.  Worse, I think they confuse rather than help readers comprehend where we are going.

Can't we just clarify that we're relatively cavalier about what a dataset is (i.e., a table row counts) for the subject part of the statement a datalink row corresponds to?  As to the object, well, leaving out the special cases of errors and service descriptors, the one thing common to all rows is that there's a URI that can be dereferenced to an octet stream of some sort (access_url).  I'd say we ought to say about as much and then say we call that a "file" for the purposes of datalink -- that gives the readers the right idea, and it avoids the "data/metadata" uglyness.

Poke me and I'll prepare a PR along these lines.

As to this PR: If nobody else shares my stylistic concerns, I'd not veto it, except that the changes in the bibliography don't belong here and should be taken out.

**Comment by Bonnarel** [comment]
As discussed last week in Strasbourg I disagree that dataset is OK for a line in a catalog. To avoid the data/metadata stylistic ugliness I will change that to "data item". Metadata are data aren't they ?

**Comment by molinaro-m** [comment]
I think there is a difference in concept between dataset and recordset (I consider a line in a catalogue to be of the latter type). Thus using dataset can be confusing. The data/metadata (or meta/data as used in other communities) can be difficult to read. I'm fine with data item and even putting a footnote if needed to clarify.

As for the bibliography changes, I agree it would be better if they are moved elsewhere.

**Comment by Bonnarel** [comment]
I removed the data/metadata ugly item and removed the bibliographich changes. Think this can be merged now

**Comment by Bonnarel** [comment]
Big conflict with master should be solved now

**Pull request merged**
