### PR TITLE
miscelaneaous service descriptor changes

### PR DESCRIPTION
**Pull request by Bonnarel**
Miscelaneous service descriptor changes proposed by Mark Taylor. They are detailed in issues #20, #21, #22, #23

### CODE REVIEW

**Comment by mbtaylor** [comment]
The modified recommendations on how to author service descriptors addressing #21, #22, #23 are about right, but the examples have not been changed.  These recommendations should be followed in the various service descriptor examples in the document to show what they look like in practice and by way of a template.

**Comment by Bonnarel** [comment]
The examples modified in the document available on the DAL wiki pages 
(page DataLink-next) were forgotten in previous version of #24. They  
have been re-added in Pullrequest #34.

Conflicts appeared trying to modify pull request #24 which sounded to be 
unsolvable.


Le 23/11/2019 à 12:16, Mark Taylor a écrit :

**Comment by msdemlei** [comment]
I *think* this PR somehow broke; if I look at the diffs, I see it removes quite a bit of language, e.g., the one on the use of fragement identifiers, something on "and very important to help user distinguish links with same semantics" (where I'll say right now I'm not so overwhelmed by the "very important" in there), and the standardID INFO, while it apparently adds the "free name" on the service descriptor from PR #35.  Could you rebuild the PR, making sure the diff is what you want it to be?

**Comment by Bonnarel** [comment]
> I _think_ this PR somehow broke; if I look at the diffs, I see it removes quite a bit of language, e.g., the one on the use of fragement identifiers, something on "and very important to help user distinguish links with same semantics" (where I'll say right now I'm not so overwhelmed by the "very important" in there), and the standardID INFO, while it apparently adds the "free name" on the service descriptor from PR #35. Could you rebuild the PR, making sure the diff is what you want it to be?

**Comment by Bonnarel** [comment]
Hi Markus,
As stated above due to unsolvable conflicts when trying to modify  the PR to add examples, I created a new PR #34 which reproduces correctly the content of this one. This one has to be closed.

**Pull request closed without merging**
