### PR TITLE
Data link #69

### PR DESCRIPTION
**Pull request by Bonnarel**
This PR is there in response to issue #52 and #55. Also creates CI preview.yml

### CODE REVIEW

**Review by mbtaylor — DISMISSED** [review]
The content of this text looks OK to me now (though it could use some line breaks).

**Comment by jd-au** [comment]
I;ve resolved the conflicts and ensured the PARAMs are closed in the example

**Comment by pdowler** [comment]
All: this question from Markus wasn't addressed:

>But would you be fine with renaming exampleURL to testQueryString so
>we have a bit of consistency with VOResource at least in nomenclature?

Mark seems OK with exampleURL and I'm on the fence... there is also the option of a sibling DALI-examples document (sibling of the endpoint in the service descriptor's accessURL value) that could offer both explanatory text and example(s) that work. Is that especially onerous for client writers? This is the 3rd way to convey a working example in the VO...

**Comment by Bonnarel** [comment]
Hi all,
Le 03/11/2021 à 02:56, Patrick Dowler a écrit :
>
> All: this question from Markus wasn't addressed:
>
>     But would you be fine with renaming exampleURL to testQueryString so
>     we have a bit of consistency with VOResource at least in nomenclature?
>
> Mark seems OK with exampleURL and I'm on the fence...
>
well exampleURL is pretty simple, but I'm not opposing testQueryString 
id preferred
>
> there is also the option of a sibling DALI-examples document (sibling 
> of the endpoint in the service descriptor's accessURL value) that 
> could offer both explanatory text and example(s) that work. Is that 
> especially onerous for client writers? This is the 3rd way to convey a 
> working example in the VO...
>
Service descriptors are not fully redondant with capability, DALI 
examples and all that sort of things for two reasons

      1 ) they are valid also for non standard services. Any VOTable 
response from whatever service may contain a service descriptor to 
describy any parameter based URL. In non standard case that's the only 
way to describe the interface

     2 ) even in the case of standard services they may be context 
dependent (an there are in genral otherwise capability could have been 
sufficient) . The simplest dependence for SODA, DataLink itself, etc... 
is to work with a predefined ID= .... But there others (OPTIONS eg)

Si I'm not sure it's that important to refer to testQyeryString or DALI 
examples here

**Comment by mbtaylor** [comment]
I'm not massively against any of the options for the detail of how to provide an example URL (exampleURL/testQueryString/DALI-examples).  DALI-examples makes some kind of sense and allows more flexibility and explanatory content.  However from a service provider's point of view, implementing it is quite a bit more effort than sticking another PARAM in alongside the existing ones, and my guess is that we'd get many fewer services providing an /examples endpoint (which some might support) than adding an example URL in a PARAM (which we could reasonably expect everybody to do).  Also, a casual reader of the service descriptor RESOURCE who's less familiar with the standards is more likely to stumble across the PARAM than go looking for an /examples document.  The name of the PARAM doesn't really matter, testQueryString could be used as a concession to standardisation.  So I'd say that's my preferred option.

**Comment by pdowler** [comment]
If we are going to nod toward VOResource (w/ testQuery) or DALI-examples (w/ examplesURL) I guess I'd prefer the latter, especially with respect to the templated URL issue and RFC6570.

**Review by pdowler — APPROVED** [review]
content previously reviewed by Mark
merged master changes in

**Pull request merged**
